In [3]:
#import pandas as pd
import csv as csv
import numpy as np

ModuleNotFoundError: No module named 'pandas'

In [11]:
df2=pd.read_csv('AAPL_stock_price_example.csv', index_col=0)

In [25]:
df2

                 Close
Date
2019-01-02  157.919998
2019-01-03  142.190002
2019-01-04  148.259995
2019-01-07  147.929993
2019-01-08  150.750000
...                ...
2019-11-20  263.190002
2019-11-21  262.010010
2019-11-22  261.779999
2019-11-25  266.369995
2019-11-26  264.290009

[229 rows x 1 columns]

In [19]:
with open('AAPL_stock_price_example.csv') as csvfile:
    reader = csv.DictReader(csvfile)
    
    print(reader.fieldnames)
    
    data = []
    for row in reader:
        data.append(row)
    
    print(data)

['Date', 'Close']
[{'Date': '2019-01-02', 'Close': '157.919998'}, {'Date': '2019-01-03', 'Close': '142.190002'}, {'Date': '2019-01-04', 'Close': '148.259995'}, {'Date': '2019-01-07', 'Close': '147.929993'}, {'Date': '2019-01-08', 'Close': '150.75'}, {'Date': '2019-01-09', 'Close': '153.309998'}, {'Date': '2019-01-10', 'Close': '153.800003'}, {'Date': '2019-01-11', 'Close': '152.289993'}, {'Date': '2019-01-14', 'Close': '150'}, {'Date': '2019-01-15', 'Close': '153.070007'}, {'Date': '2019-01-16', 'Close': '154.940002'}, {'Date': '2019-01-17', 'Close': '155.860001'}, {'Date': '2019-01-18', 'Close': '156.820007'}, {'Date': '2019-01-22', 'Close': '153.300003'}, {'Date': '2019-01-23', 'Close': '153.919998'}, {'Date': '2019-01-24', 'Close': '152.699997'}, {'Date': '2019-01-25', 'Close': '157.759995'}, {'Date': '2019-01-28', 'Close': '156.300003'}, {'Date': '2019-01-29', 'Close': '154.679993'}, {'Date': '2019-01-30', 'Close': '165.25'}, {'Date': '2019-01-31', 'Close': '166.440002'}, {'Date': '2019-02-01', 'Close': '166.520004'}, {'Date': '2019-02-04', 'Close': '171.25'}, {'Date': '2019-02-05', 'Close': '174.179993'}, {'Date': '2019-02-06', 'Close': '174.240005'}, {'Date': '2019-02-07', 'Close': '170.940002'}, {'Date': '2019-02-08', 'Close': '170.410004'}, {'Date': '2019-02-11', 'Close': '169.429993'}, {'Date': '2019-02-12', 'Close': '170.889999'}, {'Date': '2019-02-13', 'Close': '170.179993'}, {'Date': '2019-02-14', 'Close': '170.800003'}, {'Date': '2019-02-15', 'Close': '170.419998'}, {'Date': '2019-02-19', 'Close': '170.929993'}, {'Date': '2019-02-20', 'Close': '172.029999'}, {'Date': '2019-02-21', 'Close': '171.059998'}, {'Date': '2019-02-22', 'Close': '172.970001'}, {'Date': '2019-02-25', 'Close': '174.229996'}, {'Date': '2019-02-26', 'Close': '174.330002'}, {'Date': '2019-02-27', 'Close': '174.869995'}, {'Date': '2019-02-28', 'Close': '173.149994'}, {'Date': '2019-03-01', 'Close': '174.970001'}, {'Date': '2019-03-04', 'Close': '175.850006'}, {'Date': '2019-03-05', 'Close': '175.529999'}, {'Date': '2019-03-06', 'Close': '174.520004'}, {'Date': '2019-03-07', 'Close': '172.5'}, {'Date': '2019-03-08', 'Close': '172.910004'}, {'Date': '2019-03-11', 'Close': '178.899994'}, {'Date': '2019-03-12', 'Close': '180.910004'}, {'Date': '2019-03-13', 'Close': '181.710007'}, {'Date': '2019-03-14', 'Close': '183.729996'}, {'Date': '2019-03-15', 'Close': '186.119995'}, {'Date': '2019-03-18', 'Close': '188.020004'}, {'Date': '2019-03-19', 'Close': '186.529999'}, {'Date': '2019-03-20', 'Close': '188.160004'}, {'Date': '2019-03-21', 'Close': '195.089996'}, {'Date': '2019-03-22', 'Close': '191.050003'}, {'Date': '2019-03-25', 'Close': '188.740005'}, {'Date': '2019-03-26', 'Close': '186.789993'}, {'Date': '2019-03-27', 'Close': '188.470001'}, {'Date': '2019-03-28', 'Close': '188.720001'}, {'Date': '2019-03-29', 'Close': '189.949997'}, {'Date': '2019-04-01', 'Close': '191.240005'}, {'Date': '2019-04-02', 'Close': '194.020004'}, {'Date': '2019-04-03', 'Close': '195.350006'}, {'Date': '2019-04-04', 'Close': '195.690002'}, {'Date': '2019-04-05', 'Close': '197'}, {'Date': '2019-04-08', 'Close': '200.100006'}, {'Date': '2019-04-09', 'Close': '199.5'}, {'Date': '2019-04-10', 'Close': '200.619995'}, {'Date': '2019-04-11', 'Close': '198.949997'}, {'Date': '2019-04-12', 'Close': '198.869995'}, {'Date': '2019-04-15', 'Close': '199.229996'}, {'Date': '2019-04-16', 'Close': '199.25'}, {'Date': '2019-04-17', 'Close': '203.130005'}, {'Date': '2019-04-18', 'Close': '203.860001'}, {'Date': '2019-04-22', 'Close': '204.529999'}, {'Date': '2019-04-23', 'Close': '207.479996'}, {'Date': '2019-04-24', 'Close': '207.160004'}, {'Date': '2019-04-25', 'Close': '205.279999'}, {'Date': '2019-04-26', 'Close': '204.300003'}, {'Date': '2019-04-29', 'Close': '204.610001'}, {'Date': '2019-04-30', 'Close': '200.669998'}, {'Date': '2019-05-01', 'Close': '210.520004'}, {'Date': '2019-05-02', 'Close': '209.149994'}, {'Date': '2019-05-03', 'Close': '211.75'}, {'Date': '2019-05-06', 'Close': '208.479996'}, {'Date': '2019-05-07', 'Close': '202.860001'}, {'Date': '2019-05-08', 'Close': '202.899994'}, {'Date': '2019-05-09', 'Close': '200.720001'}, {'Date': '2019-05-10', 'Close': '197.179993'}, {'Date': '2019-05-13', 'Close': '185.720001'}, {'Date': '2019-05-14', 'Close': '188.660004'}, {'Date': '2019-05-15', 'Close': '190.919998'}, {'Date': '2019-05-16', 'Close': '190.080002'}, {'Date': '2019-05-17', 'Close': '189'}, {'Date': '2019-05-20', 'Close': '183.089996'}, {'Date': '2019-05-21', 'Close': '186.600006'}, {'Date': '2019-05-22', 'Close': '182.779999'}, {'Date': '2019-05-23', 'Close': '179.660004'}, {'Date': '2019-05-24', 'Close': '178.970001'}, {'Date': '2019-05-28', 'Close': '178.229996'}, {'Date': '2019-05-29', 'Close': '177.380005'}, {'Date': '2019-05-30', 'Close': '178.300003'}, {'Date': '2019-05-31', 'Close': '175.070007'}, {'Date': '2019-06-03', 'Close': '173.300003'}, {'Date': '2019-06-04', 'Close': '179.639999'}, {'Date': '2019-06-05', 'Close': '182.539993'}, {'Date': '2019-06-06', 'Close': '185.220001'}, {'Date': '2019-06-07', 'Close': '190.149994'}, {'Date': '2019-06-10', 'Close': '192.580002'}, {'Date': '2019-06-11', 'Close': '194.809998'}, {'Date': '2019-06-12', 'Close': '194.190002'}, {'Date': '2019-06-13', 'Close': '194.149994'}, {'Date': '2019-06-14', 'Close': '192.740005'}, {'Date': '2019-06-17', 'Close': '193.889999'}, {'Date': '2019-06-18', 'Close': '198.449997'}, {'Date': '2019-06-19', 'Close': '197.869995'}, {'Date': '2019-06-20', 'Close': '199.460007'}, {'Date': '2019-06-21', 'Close': '198.779999'}, {'Date': '2019-06-24', 'Close': '198.580002'}, {'Date': '2019-06-25', 'Close': '195.570007'}, {'Date': '2019-06-26', 'Close': '199.800003'}, {'Date': '2019-06-27', 'Close': '199.740005'}, {'Date': '2019-06-28', 'Close': '197.919998'}, {'Date': '2019-07-01', 'Close': '201.550003'}, {'Date': '2019-07-02', 'Close': '202.729996'}, {'Date': '2019-07-03', 'Close': '204.410004'}, {'Date': '2019-07-05', 'Close': '204.229996'}, {'Date': '2019-07-08', 'Close': '200.020004'}, {'Date': '2019-07-09', 'Close': '201.240005'}, {'Date': '2019-07-10', 'Close': '203.229996'}, {'Date': '2019-07-11', 'Close': '201.75'}, {'Date': '2019-07-12', 'Close': '203.300003'}, {'Date': '2019-07-15', 'Close': '205.210007'}, {'Date': '2019-07-16', 'Close': '204.5'}, {'Date': '2019-07-17', 'Close': '203.350006'}, {'Date': '2019-07-18', 'Close': '205.660004'}, {'Date': '2019-07-19', 'Close': '202.589996'}, {'Date': '2019-07-22', 'Close': '207.220001'}, {'Date': '2019-07-23', 'Close': '208.839996'}, {'Date': '2019-07-24', 'Close': '208.669998'}, {'Date': '2019-07-25', 'Close': '207.020004'}, {'Date': '2019-07-26', 'Close': '207.740005'}, {'Date': '2019-07-29', 'Close': '209.679993'}, {'Date': '2019-07-30', 'Close': '208.779999'}, {'Date': '2019-07-31', 'Close': '213.039993'}, {'Date': '2019-08-01', 'Close': '208.429993'}, {'Date': '2019-08-02', 'Close': '204.020004'}, {'Date': '2019-08-05', 'Close': '193.339996'}, {'Date': '2019-08-06', 'Close': '197'}, {'Date': '2019-08-07', 'Close': '199.039993'}, {'Date': '2019-08-08', 'Close': '203.429993'}, {'Date': '2019-08-09', 'Close': '200.990005'}, {'Date': '2019-08-12', 'Close': '200.479996'}, {'Date': '2019-08-13', 'Close': '208.970001'}, {'Date': '2019-08-14', 'Close': '202.75'}, {'Date': '2019-08-15', 'Close': '201.740005'}, {'Date': '2019-08-16', 'Close': '206.5'}, {'Date': '2019-08-19', 'Close': '210.350006'}, {'Date': '2019-08-20', 'Close': '210.360001'}, {'Date': '2019-08-21', 'Close': '212.639999'}, {'Date': '2019-08-22', 'Close': '212.460007'}, {'Date': '2019-08-23', 'Close': '202.639999'}, {'Date': '2019-08-26', 'Close': '206.490005'}, {'Date': '2019-08-27', 'Close': '204.160004'}, {'Date': '2019-08-28', 'Close': '205.529999'}, {'Date': '2019-08-29', 'Close': '209.009995'}, {'Date': '2019-08-30', 'Close': '208.740005'}, {'Date': '2019-09-03', 'Close': '205.699997'}, {'Date': '2019-09-04', 'Close': '209.190002'}, {'Date': '2019-09-05', 'Close': '213.279999'}, {'Date': '2019-09-06', 'Close': '213.259995'}, {'Date': '2019-09-09', 'Close': '214.169998'}, {'Date': '2019-09-10', 'Close': '216.699997'}, {'Date': '2019-09-11', 'Close': '223.589996'}, {'Date': '2019-09-12', 'Close': '223.089996'}, {'Date': '2019-09-13', 'Close': '218.75'}, {'Date': '2019-09-16', 'Close': '219.899994'}, {'Date': '2019-09-17', 'Close': '220.699997'}, {'Date': '2019-09-18', 'Close': '222.770004'}, {'Date': '2019-09-19', 'Close': '220.960007'}, {'Date': '2019-09-20', 'Close': '217.729996'}, {'Date': '2019-09-23', 'Close': '218.720001'}, {'Date': '2019-09-24', 'Close': '217.679993'}, {'Date': '2019-09-25', 'Close': '221.029999'}, {'Date': '2019-09-26', 'Close': '219.889999'}, {'Date': '2019-09-27', 'Close': '218.820007'}, {'Date': '2019-09-30', 'Close': '223.970001'}, {'Date': '2019-10-01', 'Close': '224.589996'}, {'Date': '2019-10-02', 'Close': '218.960007'}, {'Date': '2019-10-03', 'Close': '220.820007'}, {'Date': '2019-10-04', 'Close': '227.009995'}, {'Date': '2019-10-07', 'Close': '227.059998'}, {'Date': '2019-10-08', 'Close': '224.399994'}, {'Date': '2019-10-09', 'Close': '227.029999'}, {'Date': '2019-10-10', 'Close': '230.089996'}, {'Date': '2019-10-11', 'Close': '236.210007'}, {'Date': '2019-10-14', 'Close': '235.869995'}, {'Date': '2019-10-15', 'Close': '235.320007'}, {'Date': '2019-10-16', 'Close': '234.369995'}, {'Date': '2019-10-17', 'Close': '235.279999'}, {'Date': '2019-10-18', 'Close': '236.410004'}, {'Date': '2019-10-21', 'Close': '240.509995'}, {'Date': '2019-10-22', 'Close': '239.960007'}, {'Date': '2019-10-23', 'Close': '243.179993'}, {'Date': '2019-10-24', 'Close': '243.580002'}, {'Date': '2019-10-25', 'Close': '246.580002'}, {'Date': '2019-10-28', 'Close': '249.050003'}, {'Date': '2019-10-29', 'Close': '243.289993'}, {'Date': '2019-10-30', 'Close': '243.259995'}, {'Date': '2019-10-31', 'Close': '248.759995'}, {'Date': '2019-11-01', 'Close': '255.820007'}, {'Date': '2019-11-04', 'Close': '257.5'}, {'Date': '2019-11-05', 'Close': '257.130005'}, {'Date': '2019-11-06', 'Close': '257.23999'}, {'Date': '2019-11-07', 'Close': '259.429993'}, {'Date': '2019-11-08', 'Close': '260.140015'}, {'Date': '2019-11-11', 'Close': '262.200012'}, {'Date': '2019-11-12', 'Close': '261.959991'}, {'Date': '2019-11-13', 'Close': '264.470001'}, {'Date': '2019-11-14', 'Close': '262.640015'}, {'Date': '2019-11-15', 'Close': '265.76001'}, {'Date': '2019-11-18', 'Close': '267.100006'}, {'Date': '2019-11-19', 'Close': '266.290009'}, {'Date': '2019-11-20', 'Close': '263.190002'}, {'Date': '2019-11-21', 'Close': '262.01001'}, {'Date': '2019-11-22', 'Close': '261.779999'}, {'Date': '2019-11-25', 'Close': '266.369995'}, {'Date': '2019-11-26', 'Close': '264.290009'}]

In [2]:
a = np.arange(5)

NameError: name 'np' is not defined